// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1pWiDL6bn5tvlOFVeitfFece6PIqAZow',
    appId: '1:605466185443:web:34e67adecd21b415cb3fd6',
    messagingSenderId: '605466185443',
    projectId: 'hopp-kapindaa',
    authDomain: 'hopp-kapindaa.firebaseapp.com',
    storageBucket: 'hopp-kapindaa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8LCK4VEH6ZSXqWJoPS0YkmyGCEEtAsqY',
    appId: '1:605466185443:android:cea0ae5b77e4cad7cb3fd6',
    messagingSenderId: '605466185443',
    projectId: 'hopp-kapindaa',
    storageBucket: 'hopp-kapindaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmXMfgMILviYxD4B6gkktzA8r9qSsP5P8',
    appId: '1:605466185443:ios:34c02d8f122a73bfcb3fd6',
    messagingSenderId: '605466185443',
    projectId: 'hopp-kapindaa',
    storageBucket: 'hopp-kapindaa.firebasestorage.app',
    iosBundleId: 'com.hoppkapinda.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmXMfgMILviYxD4B6gkktzA8r9qSsP5P8',
    appId: '1:605466185443:ios:0610f0e9f119ad3dcb3fd6',
    messagingSenderId: '605466185443',
    projectId: 'hopp-kapindaa',
    storageBucket: 'hopp-kapindaa.firebasestorage.app',
    iosBundleId: 'com.example.hoppKapinda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1pWiDL6bn5tvlOFVeitfFece6PIqAZow',
    appId: '1:605466185443:web:0e711973e3ec23fbcb3fd6',
    messagingSenderId: '605466185443',
    projectId: 'hopp-kapindaa',
    authDomain: 'hopp-kapindaa.firebaseapp.com',
    storageBucket: 'hopp-kapindaa.firebasestorage.app',
  );
}
